import './globals.css'
import { Saira } from 'next/font/google' // biblioteca do next das fontes do google
import { Header } from '@/components/header'


const saira = Saira({ 
	weight: ['300', '400','500', '600'],
	subsets: ['latin'] }) // importando weight e subsets

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
		<Header/>
		{children}
	  </body>
    </html>
  )
}
